#!/bin/bash
echo "To check the logs, run this command:"
echo ""
echo "1. Go to your Supabase dashboard"
echo "2. Navigate to Edge Functions > check-live-and-notify"
echo "3. Click on 'Logs' tab"
echo ""
echo "Look for these log messages:"
echo "  - '📅 Today is...'"
echo "  - '🕐 [Prayer] begins at...'"
echo "  - '✅ NEAR PRAYER:' or '⏳ Not near any prayer'"
echo "  - '📢 Sending [type] notification' or 'Sending generic notification'"
echo ""
echo "Or use the Supabase CLI:"
echo "supabase functions logs check-live-and-notify --limit 100"
